development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: found_development
  pool: 5
  username: rails
  password: rails
  host: localhost
  
test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: found_test
  pool: 5
  username: rails
  password: rails
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: found_production
  pool: 5
  username: rails
  password: rails
  host: localhost
